### ISSUE TITLE
[FIXED] [General] Links still pointing to home page

### ISSUE THREAD

**Issue by isaacsgraphic** [thinkpixels/devtools.online#17]
Within Design #mockups,  both invision app and mockingbird do not have the correct links- they just take me back to "Everything". Also, [Marvel app](https://marvelapp.com/) is a major competitor in this field, and might be a good addition.

**Comment by thinkpixels** [comment]
Thanks for the heads up, I'll be sure to fix this today! And I'll definitely add Marvel App to the list.
