### ISSUE TITLE
[General] Firebase limit reached

### ISSUE THREAD

**Issue by davidrayoussef** [thinkpixels/devtools.online#18]
Most likely temporary due to traffic spike, but may need to upgrade or scale in the future.
_FIREBASE WARNING: Specified Firebase has reached its Peak Connections limit._

**Comment by danielrw7** [comment]
I'm getting this same error.

**Comment by thinkpixels** [comment]
Reddit hugged my site to death while I was sleeping. I upgraded my account this morning so this is fixed now
