### ISSUE TITLE
[Bug] Number of items on sidebar different from items being shown

### ISSUE THREAD

**Issue by torresandres** [thinkpixels/devtools.online#24]
On the left says 18 but only 3 elements are being shown.

URL: https://www.devtools.online/#!/design/applications/
Screenshot: 
![capture](https://cloud.githubusercontent.com/assets/1640549/14772926/06c51652-0a7a-11e6-938f-b5f365f22332.PNG)

**Comment by thinkpixels** [comment]
Good catch, thank you!
